### ISSUE TITLE
A question about the adjacency matrix

### ISSUE THREAD

**Issue by HX-idiot** [csyanbin/TPN-pytorch#2]
Hello, it is really a good work!
I am confused of the value of diagonal when constructing the adjacency matrix, in your code, you didn't mask the diagonal, which will make the value of diagonal near to 1. does that limit the result of transductive (S is near to Identity matrix under this condition)?

**Comment by csyanbin** [comment]
Hi, thanks for your interest in our paper.
This is the same issue as here: https://github.com/csyanbin/TPN/issues/2#issuecomment-463913199

Currently, we haven't experimented with Wii=0.
In LLGC (zhou et al,2004), they set Wii=0 to avoid self-reinforcement.
But in our paper, we think it not necessary to prevent this self-reinforcement.

I will try the setting with Wii=0 in the future.
